### ISSUE TITLE
Integrate banners in the administration view

### ISSUE THREAD

**Issue by kpsherva** [inveniosoftware/invenio-banners#4]
### Tasks

- Task 1:
  - [x] make sure the [InvenioRDM architecture](https://inveniordm.docs.cern.ch/develop/), in particular the `resource` and `service` layers, is well understood.
  - [x] refactor the module to implement the resource/service pattern for CREATE operation.
- Task 2: 
  - [x] refactor the module to implement the resource/service pattern for all other operations.
- Task 3:
  - [x] convert the module to the latest Invenio best practices for packaging, code linting and testing (integrate `black`, move to `setup.cfg`, ensure the usage of the latest `pytest-invenio`. Check how it has been done in other modules).
  - [x] change the `macro` to use Semantic-UI instead of Bootstrap.
- Task 4:
  - [ ] Improve banners search operation 
- Task 5:
  - [ ] integrate `invenio-administration` to be able to CRUD banners via the Administration web UI.
- Task 6:
  - [ ]  after release, add this module and macro to `invenio-app-rdm` base template.

### Testing
- [ ] make sure it can be correctly installed in InvenioRDM `master`.
- [x] test that a banner is displayed, when added/activated programmatically.

### Releasing
- [ ] Release the package as a package version and add it to `invenio-app-rdm`.

**Comment by ntarocco** [comment]
@anikachurilova you might want to add a new issue per checkbox, so that you can create a dedicate PR for each/group of them and then close them.
